### PR TITLE
Adding anatures

### PR DESCRIPTION
**Pull request by csomes**
Put in all the anatures we have sprites for (added sprites and put names into Species enum), Gabe still needs to send me some images but I figured I'd push these up cause it's such an old story!

### CODE REVIEW

**Comment by csomes** [comment]
Looks like I accidentally included the SQL file, should I delete the file and then push up? Could use some advice on this one

**Comment by HMRich** [comment]
I'm not sure. Right now your branch is saying that it is having merging conflicts. What file are you questioning?

But I am seeing the `.DC_Store` file in every folder leading up to resources folder. Is that needed?

**Comment by csomes** [comment]
Hunter, any idea how I would correct that? My side says that the database file is conflicting

**Comment by csomes** [comment]
This PR is officially dead. New version has been put up for review

**Pull request closed without merging**
